[project]
name = "install-proper-polars"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["authors"]
dependencies = [
    "py-cpuinfo>=9.0.0",
    "setuptools>=80.9.0",
    "wheel>=0.45.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"